// Generated by GraphWalker (http://www.graphwalker.org)
package com.alskami.graphwalker.smoketest;

import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Vertex;

//@Model(file = "com/alskami/graphwalker/smoketest/Model_smoke_backend.graphml")
public interface As_generated_Model_smoke_backend {

    @Edge()
    void e_make_a_call();

    @Vertex()
    void v_Unauthorized();

    @Edge()
    void e_add10dollars();

    @Vertex()
    void v_CreditAdded();

    @Edge()
    void e_login();

    @Vertex()
    void v_LoggedIn();

    @Vertex()
    void v_CallAccounted();

    @Edge()
    void e_log_out();

    @Edge()
    void e_signup();
}
